// Note: Generated by AI assistant
//! Test crate for ISM implementation.
//! Contains test cases for both runtime behavior and compile-time checks.

pub mod text;  // Runtime tests for text-based implementation
pub mod derive;  // Compile-time tests for derive macros 