// Note: Generated by AI assistant
use ism_derive::{Serialize, Deserialize};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
#[derive(Serialize, Deserialize)]
struct EmptyStruct {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
#[derive(Serialize, Deserialize)]
struct UnitStruct;

fn main() {
    let msg = EmptyStruct {};
    let ism_msg = msg.serialize();
    let decoded = EmptyStruct::deserialize(ism_msg).unwrap();
    assert_eq!(msg, decoded);

    let msg = UnitStruct;
    let ism_msg = msg.serialize();
    let decoded = UnitStruct::deserialize(ism_msg).unwrap();
    assert_eq!(msg, decoded);
} 