// Note: Generated by AI assistant
use ism::text::Message;
use std::collections::HashMap;

#[test]
fn test_empty_list() {
    let msg = Message::List(vec![]);
    let json = serde_json::to_string(&msg).unwrap();
    assert_eq!(json, "[]");
}

#[test]
fn test_empty_table() {
    let msg = Message::Table(HashMap::new());
    let json = serde_json::to_string(&msg).unwrap();
    assert_eq!(json, "{}");
}

#[test]
fn test_empty_string() {
    let msg = Message::Text("".to_string());
    let json = serde_json::to_string(&msg).unwrap();
    assert_eq!(json, r#""""#);
} 