// Note: Generated by AI assistant
use ism_derive::{Serialize, Deserialize};

// Successful recursive type
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
#[derive(Serialize, Deserialize)]
struct RecursiveMessage {
    value: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    next: Option<Box<RecursiveMessage>>,
}

#[test]
fn test_recursive_message() {
    let msg = RecursiveMessage {
        value: "a".to_string(),
        next: Some(Box::new(RecursiveMessage {
            value: "b".to_string(),
            next: None,
        })),
    };

    let ism_msg = msg.serialize();
    let decoded = RecursiveMessage::deserialize(ism_msg).unwrap();
    assert_eq!(msg, decoded);
}

// Compile failure tests
#[test]
fn test_compile_failures() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/derive/fail/*.rs");
} 