// Note: Generated by AI assistant
//! Test module for derive macro compilations.
//! All test cases are in tests/derive directory:
//! - pass/*.rs: Successful compilation cases
//! - fail/*.rs: Expected compilation failure cases

#[test]
fn test_compile_cases() {
    let t = trybuild::TestCases::new();
    // Test successful compilation
    t.pass("tests/derive/pass/*.rs");
    // Test compilation failures
    t.compile_fail("tests/derive/fail/*.rs");
} 